---
- name: Install Packages in Ansible 2.11+
  hosts: all
  tasks:
    - name: Installing Packages
      apt:
        name:
          - nginx
          - postgresql
        state: present

    - name: Install GCC, Make
      apt:
        name: ['gcc','make']
        state: present