---
- name: Variable Playbook
  hosts: website
  vars:
    salutations: Hello!
    students:
      - Mark
      - Jenny
      - Tony
    superhero:
      Mark: Spidy
      Jenny: Ben10
      Tony: Superman

  tasks:
    - name: Ansible Basic Variable Usages
      debug:
        msg: "{{ salutations }} {{ students[2] }} You got {{superhero.Tony}}"
